language: c

before_install:
  - sudo apt-get install build-essential lua5.1 freeglut3-dev libglew-dev libglu1-mesa-dev libxmu-dev libxi-dev libxxf86vm-dev luarocks -y
  - git clone https://github.com/Olivine-Labs/busted
  - sudo luarocks install busted
  - sudo luarocks install luacov-coveralls
  # Oh, the hacks.
  - cp `which busted` test_runner
  - sed -i -e 's/-lluarocks.loader //g' test_runner
  - sed -i -e 's/\/usr\/bin\/lua/\.\/ci\/moai_linux/g' test_runner

script:
  - ./test_runner test

after_success:
  - make test-cov
